### ISSUE TITLE
Improve Robustness of Adding new Applications

### ISSUE THREAD

**Issue by will-kyaria** [willmbennett/kyaria#140]
A key aspect of job application management is the ability to create new job applications. Currently the form submission isn't that great, and there's not a lot of robustness.

**Todo:**
- [ ] Explore methods of increasing reliability
- [ ] Potential for async job
- [ ] Improve data validation

Here's the current code
```javascript
    const handleCopyResume = async (data: ResumeClass) => {
        try {
            const resumeCopy: Partial<ResumeClass> = { ...data };

            delete resumeCopy._id;
            delete resumeCopy.createdAt;
            delete resumeCopy.updatedAt;
            delete resumeCopy.userId;

            const userResumeWithIds = { fromTemplate: true, ...resumeCopy, userId };
            const resumeId = await createResumeAction(userResumeWithIds, '/');

            if (resumeId) {
                return resumeId
            }
        } catch (error) {
            console.error('Error during resume copy:', error);
        }
    }

    const onSubmit: SubmitHandler<FormFields> = async (data) => {
        try {
            setLoading(true);

            // Make the API call to your Next.js route
            const response = await fetch(`/api/diffbot/job?url=${encodeURIComponent(data.input)}`, {
                method: 'GET',
                headers: {
                    'Content-Type': 'application/json',
                },
            });

            if (!response.ok) {
                throw new Error('Failed to fetch data from the API.');
            }

            const apiData = await response.json();

            //console.log(apiData)

            if (apiData) {

                const transformedData = transformDiffBotApiResponse(apiData, data.input)
                // Handle the API response data here (e.g., setValues, etc.)
                console.log(transformedData)

                const jobId = await createJobAction(transformedData, path)
                console.log('jobId: ', jobId)
                console.log('selectedResume: ', selectedResume)
                if (jobId && selectedResume) {
                    console.log('Made it to resume creation')
                    const newResumeId = await handleCopyResume(selectedResume)
                    console.log('newResumeId: ', newResumeId)

                    if (newResumeId) {
                        console.log('Made it to app creation')
                        const userApp: Partial<AppClass> = {
                            job: jobId,
                            userId: userId,
                            emails: emails,
                            userStory: profile.story || '',
                            profile: profile._id,
                            userResume: newResumeId
                        }
                        const appId = await createAppAction(userApp, path);
                        console.log('appId: ', appId)
                        console.log('App created Successfully')
                        if (appId)
                            //console.log(userApp)
                            router.push(`${appId}`)
                    }
                }
            }


        } catch (error) {
            console.error(error);
            // Handle the error (e.g., display an error message to the user)
            alert('Creating job failed')
            router.refresh()
        } finally {
            setLoading(false);
        }

    };
```
